const fs=require('node:fs');
const path=require('node:path');
const out='dist';
if(!fs.existsSync(out)) throw new Error('dist must exist before traffic postbuild');

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origin='https://www.buildwithleftovers.com';
const toolCss=`
<style>
.traffic-wrap{max-width:1120px;margin:0 auto;padding:0 22px 64px}.traffic-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:22px;align-items:start}.traffic-card{background:#fff;border:1px solid rgba(23,63,53,.16);border-radius:22px;padding:24px;box-shadow:0 16px 42px rgba(23,63,53,.07)}.traffic-card h2,.traffic-card h3{margin-top:0}.traffic-fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.traffic-fields label{display:flex;flex-direction:column;gap:7px;font-weight:750}.traffic-fields label.wide{grid-column:1/-1}.traffic-fields input,.traffic-fields textarea,.traffic-fields select{box-sizing:border-box;width:100%;padding:12px 13px;border:1px solid rgba(23,63,53,.27);border-radius:12px;background:#fff;color:inherit;font:inherit}.traffic-fields textarea{min-height:132px;resize:vertical}.traffic-run{width:100%;margin-top:18px;border:0;border-radius:999px;padding:13px 18px;font:inherit;font-weight:850;background:#173f35;color:#fff;cursor:pointer}.traffic-stats{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.traffic-stat{padding:15px;border:1px solid rgba(23,63,53,.14);border-radius:16px;background:rgba(23,63,53,.035)}.traffic-stat b{display:block;font-size:1.45rem;margin-bottom:4px}.traffic-summary{padding:15px;border-radius:14px;background:rgba(23,63,53,.08);line-height:1.55}.traffic-detail{font-size:.92rem;line-height:1.55}.traffic-allocation{display:grid;gap:8px}.traffic-allocation div{padding:10px 12px;border-radius:10px;background:rgba(23,63,53,.05)}.traffic-error{color:#9b2c2c;font-weight:700}.traffic-copy{max-width:900px}.traffic-copy p,.traffic-copy li{line-height:1.65}.traffic-copy ul{padding-left:22px}@media(max-width:760px){.traffic-grid,.traffic-fields{grid-template-columns:1fr}.traffic-fields label.wide{grid-column:auto}.traffic-stats{grid-template-columns:1fr 1fr}}
</style>`;

function schema(slug,name,desc,faqs){
 const graph=[{'@type':'WebApplication',name,url:`${origin}/${slug}`,applicationCategory:'UtilitiesApplication',isAccessibleForFree:true,description:desc},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${origin}/`},{'@type':'ListItem',position:2,name,item:`${origin}/${slug}`}]}];
 return `<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph})}</script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))})}</script>`;
}
function related(links){return `<section class="related traffic-growth-links"><span class="eyebrow">RELATED LEFTOVER TOOLS</span><h2>Keep planning with exact measurements</h2><div class="related-grid">${links.map(([u,t,d])=>`<a href="${u}"><b>${t}</b><span>${d} →</span></a>`).join('')}</div></section>`;}
function toolPage(o){
 const faqHtml=o.faqs.map(([q,a],i)=>`<div><strong>${String(i+1).padStart(2,'0')}</strong><h3>${esc(q)}</h3><p>${esc(a)}</p></div>`).join('');
 return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(o.title)}</title><meta name="description" content="${esc(o.desc)}"><link rel="canonical" href="${origin}/${o.slug}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta name="theme-color" content="#173f35"><meta property="og:title" content="${esc(o.title)}"><meta property="og:description" content="${esc(o.desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}/${o.slug}"><meta property="og:image" content="${origin}/logo.svg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/style.css?v=20260912-traffic">${toolCss}${schema(o.slug,o.name,o.desc,o.faqs)}</head><body data-traffic-tool="${o.tool}"><header><a class="brand" href="/"><img src="/logo.svg" alt="Leftover"><span class="brand-word">Leftover<small>PLAN SMART. WASTE LESS.</small></span></a><nav><a href="/what-can-i-make">Project finder</a><a href="/#popular-calculators">Calculators</a><a href="/about">About</a></nav></header><main><nav class="guide-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>${esc(o.name)}</span></nav><section class="material-page-hero"><div><span class="eyebrow">${esc(o.eyebrow)}</span><h1>${esc(o.h1)}</h1><p>${esc(o.intro)}</p><a class="cta" href="#calculator">Use the calculator →</a></div></section><section class="traffic-wrap" id="calculator"><div class="traffic-grid"><form class="traffic-card" id="trafficForm" onsubmit="return false"><span class="eyebrow">FREE BROWSER TOOL</span><h2>${esc(o.formTitle)}</h2><div class="traffic-fields">${o.fields}</div><button class="traffic-run" id="trafficRun" type="button">Calculate →</button><p id="trafficError" class="traffic-error" role="alert" hidden></p></form><section class="traffic-card" id="trafficResult" aria-live="polite"><span class="eyebrow">RESULT</span><h2>${esc(o.resultTitle)}</h2>${o.result}</section></div></section><section class="how seo-copy traffic-copy"><span class="eyebrow">HOW TO USE IT</span><h2>${esc(o.copyTitle)}</h2>${o.copy}</section><section class="how seo-copy"><span class="eyebrow">COMMON QUESTIONS</span><h2>${esc(o.name)} FAQ</h2><div class="steps">${faqHtml}</div></section>${related(o.links)}</main><footer><a href="/">Leftover</a><nav><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></nav></footer><script src="/traffic-calculators.js?v=20260912"></script></body></html>`;
}
function guidePage(o){const faqHtml=o.faqs.map(([q,a],i)=>`<div><strong>${String(i+1).padStart(2,'0')}</strong><h3>${esc(q)}</h3><p>${esc(a)}</p></div>`).join('');return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(o.title)}</title><meta name="description" content="${esc(o.desc)}"><link rel="canonical" href="${origin}/${o.slug}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta name="theme-color" content="#173f35"><link rel="stylesheet" href="/style.css?v=20260912-traffic">${schema(o.slug,o.name,o.desc,o.faqs)}</head><body><header><a class="brand" href="/"><img src="/logo.svg" alt="Leftover"><span class="brand-word">Leftover<small>PLAN SMART. WASTE LESS.</small></span></a><nav><a href="/deck-board-calculator">Deck spacing calculator</a><a href="/decking">Decking</a><a href="/about">About</a></nav></header><main><nav class="guide-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/decking">Decking</a><span>/</span><span>${esc(o.name)}</span></nav><section class="material-page-hero"><div><span class="eyebrow">DECK BOARD SPACING GUIDE</span><h1>${esc(o.h1)}</h1><p>${esc(o.intro)}</p><a class="cta" href="/deck-board-calculator">Open deck spacing calculator →</a></div></section><section class="how seo-copy traffic-copy">${o.body}</section><section class="how seo-copy"><span class="eyebrow">COMMON QUESTIONS</span><h2>${esc(o.name)} FAQ</h2><div class="steps">${faqHtml}</div></section>${related(o.links)}</main><footer><a href="/">Leftover</a><nav><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></nav></footer></body></html>`;}

const stats=`<div class="traffic-stats"><div class="traffic-stat"><b id="r1">—</b><span id="l1">Primary result</span></div><div class="traffic-stat"><b id="r2">—</b><span id="l2">Secondary result</span></div><div class="traffic-stat"><b id="r3">—</b><span id="l3">Existing stock</span></div><div class="traffic-stat"><b id="r4">—</b><span id="l4">Purchase gap / surplus</span></div></div><p class="traffic-summary" id="trafficSummary">Enter your measurements to calculate.</p><div class="traffic-allocation" id="trafficAllocation"></div><p class="traffic-detail" id="trafficNote"></p>`;
const linearFields=(stock='8',cuts='36 x 4\n24 x 2\n18 x 2')=>`<label>Stock piece length<span><input id="stockLength" type="number" min="0.01" step="any" value="${stock}" inputmode="decimal"> ft</span></label><label>Saw kerf<span><input id="kerf" type="number" min="0" step="any" value="0.125" inputmode="decimal"> in</span></label><label>Full stock pieces already owned<span><input id="owned" type="number" min="0" step="1" value="0" inputmode="numeric"></span></label><label class="wide">Required cuts — one line per length × quantity<textarea id="cuts" spellcheck="false">${cuts}</textarea><small>Use decimal inches, for example: 36 x 4. The calculator packs the longest cuts first and includes kerf between cuts.</small></label>`;

const pages=[
 {slug:'lumber-cut-calculator',tool:'linear',name:'Lumber Cut Calculator',title:'Lumber Cut Calculator – Cut List & Stock Boards | Leftover',desc:'Free lumber cut calculator. Enter stock length, saw kerf and required cuts to estimate how many boards you need, see cut allocation and compare against boards you already own.',eyebrow:'CUT LIST / STOCK BOARDS / KERF',h1:'Lumber Cut Calculator',intro:'Turn a cut list into a stock-board plan before you buy. Enter the cuts, board length and saw kerf, then compare the result with lumber you already own.',formTitle:'Pack your cuts onto stock boards',fields:linearFields('8','36 x 4\n24 x 2\n18 x 2'),resultTitle:'Your cut-list estimate',result:stats,copyTitle:'Use a cut list instead of total footage alone',copy:'<p>Total board footage can look sufficient while an individual long cut still does not fit. This calculator keeps every requested cut intact, accounts for saw kerf between cuts, and groups cuts onto whole stock boards. It is especially useful for 2×4s, 2×6s and other straight lumber where the cross-section is already known.</p><p>The packing method sorts the longest cuts first and fits them into the earliest board with enough remaining length. It is a practical planning heuristic, not a certified global optimum. Verify grain, defects, end checks, structural grade and real saw setup before cutting.</p>',faqs:[['Can I use this as a 2x4 cut calculator?','Yes. Set the stock length to the 2x4 length you have or plan to buy, then enter each finished cut length in inches.'],['Does the calculator include saw kerf?','Yes. Kerf is applied between cuts on the same stock board.'],['Why is a cut list better than total linear feet?','Because total footage cannot prove that each individual requested length physically fits a stock board.']],links:[['/lumber','Leftover lumber planner','Compare a project with full boards and offcuts you already own'],['/what-can-i-make-with-leftover-2x4s','Projects for leftover 2×4s','Start from the boards in your garage'],['/plywood-cut-calculator','Plywood cut calculator','Plan rectangular sheet-goods cuts']]},
 {slug:'flooring-plank-calculator',tool:'flooring',name:'Flooring Plank Calculator',title:'Flooring Plank Calculator – Planks, Boxes & Leftovers | Leftover',desc:'Calculate flooring planks and boxes from room size, plank dimensions and waste, then subtract the planks you already own to see the remaining purchase gap.',eyebrow:'PLANK COUNT / BOXES / LEFTOVERS',h1:'Flooring Plank Calculator',intro:'Calculate the planks and boxes a rectangular floor needs, then subtract leftover planks you already have before buying another carton.',formTitle:'Measure the room and plank',fields:'<label>Room length<span><input id="roomLength" type="number" min="0.01" step="any" value="12"> ft</span></label><label>Room width<span><input id="roomWidth" type="number" min="0.01" step="any" value="10"> ft</span></label><label>Plank length<span><input id="pieceLength" type="number" min="0.01" step="any" value="48"> in</span></label><label>Plank width<span><input id="pieceWidth" type="number" min="0.01" step="any" value="7.5"> in</span></label><label>Planning waste<span><input id="waste" type="number" min="0" max="100" step="any" value="8"> %</span></label><label>Planks per box<span><input id="perBox" type="number" min="1" step="1" value="8"></span></label><label class="wide">Usable leftover planks already owned<span><input id="owned" type="number" min="0" step="1" value="0"></span></label>',resultTitle:'Your flooring quantity',result:stats,copyTitle:'Count purchasable planks, not just square feet',copy:'<p>Flooring is normally purchased as whole planks or cartons. The calculator converts the room area into a plank count, applies the planning waste percentage, and then rounds the purchase requirement to whole pieces and boxes. It also subtracts usable matching planks you already own.</p><p>Real installations can require more material for angled rooms, pattern direction, stagger rules, damaged boards, minimum end joints and manufacturer requirements. Keep dye lot or production-batch compatibility in mind when mixing saved material with new flooring.</p>',faqs:[['How many flooring planks do I need?','Divide the waste-adjusted room area by the face area of one plank and round up to a whole plank.'],['Does this calculator subtract leftover planks?','Yes. Enter the number of usable matching planks you already own to see the remaining purchase gap.'],['Does plank direction matter?','It can affect cuts and waste. This calculator is a quantity estimate; use the main Leftover flooring planner for a more reuse-focused layout check.']],links:[['/flooring','Leftover flooring planner','Check whether saved planks can physically finish the room'],['/leftover-flooring-repair','Flooring repair planner','Plan a repair around leftover matching planks'],['/what-can-i-make-with-leftover-flooring','Leftover flooring ideas','Find small projects that fit saved planks']]},
 {slug:'tile-coverage-calculator',tool:'tile',name:'Tile Coverage Calculator',title:'Tile Coverage Calculator – Tiles, Boxes & Leftover Tile | Leftover',desc:'Calculate tile count and boxes from room dimensions, tile size and waste, then subtract leftover tiles you already own to see the purchase gap.',eyebrow:'TILE COUNT / BOXES / LEFTOVERS',h1:'Tile Coverage Calculator',intro:'Turn room dimensions and tile size into a whole-tile count, then credit usable matching tiles you already have before buying more.',formTitle:'Measure the surface and tile',fields:'<label>Surface length<span><input id="roomLength" type="number" min="0.01" step="any" value="8"> ft</span></label><label>Surface width<span><input id="roomWidth" type="number" min="0.01" step="any" value="6"> ft</span></label><label>Tile length<span><input id="pieceLength" type="number" min="0.01" step="any" value="12"> in</span></label><label>Tile width<span><input id="pieceWidth" type="number" min="0.01" step="any" value="12"> in</span></label><label>Planning waste<span><input id="waste" type="number" min="0" max="100" step="any" value="10"> %</span></label><label>Tiles per box<span><input id="perBox" type="number" min="1" step="1" value="10"></span></label><label class="wide">Usable matching tiles already owned<span><input id="owned" type="number" min="0" step="1" value="0"></span></label>',resultTitle:'Your tile quantity',result:stats,copyTitle:'Calculate whole tiles and the actual purchase gap',copy:'<p>The tool multiplies surface length by width, converts one tile to square feet, adds your waste allowance and rounds up to a whole tile. Enter leftover matching tiles to reduce the remaining purchase count before the result is converted to boxes.</p><p>Pattern, grout joints, diagonal layouts, niches, broken tiles and edge cuts can change real usage. For saved tile, also confirm size, thickness, finish and batch appearance before mixing old and new material.</p>',faqs:[['How many 12×12 tiles cover one square foot?','One 12×12-inch tile has a face area of one square foot before grout joints and cutting waste.'],['Can I enter tiles I already own?','Yes. The calculator subtracts usable matching tiles from the waste-adjusted tile count.'],['Does the calculator handle diagonal patterns?','Not directly. Increase the planning waste to reflect the pattern and verify the final layout before ordering.']],links:[['/tile','Leftover tile planner','Test saved full tiles and measured scraps against a project'],['/leftover-tile-backsplash','Leftover tile backsplash','Plan a backsplash around saved tile'],['/how-many-square-feet-20-12x12-tiles','20 12×12 tiles coverage','See a worked leftover-tile example']]},
 {slug:'wallpaper-roll-calculator',tool:'wallpaper',name:'Wallpaper Roll Calculator',title:'Wallpaper Roll Calculator – Pattern Repeat & Rolls Needed | Leftover',desc:'Calculate wallpaper rolls using wall width, height, roll dimensions, trim allowance and pattern repeat, then subtract rolls you already own.',eyebrow:'DROPS / PATTERN REPEAT / ROLLS',h1:'Wallpaper Roll Calculator',intro:'Calculate full-height drops and whole rolls using the real roll size and vertical pattern repeat instead of relying on area alone.',formTitle:'Measure the wall and roll',fields:'<label>Total wall width<span><input id="wallWidth" type="number" min="0.01" step="any" value="36"> ft</span></label><label>Wall height<span><input id="wallHeight" type="number" min="0.01" step="any" value="8"> ft</span></label><label>Roll width<span><input id="rollWidth" type="number" min="0.01" step="any" value="20.5"> in</span></label><label>Roll length<span><input id="rollLength" type="number" min="0.01" step="any" value="33"> ft</span></label><label>Vertical pattern repeat<span><input id="repeat" type="number" min="0" step="any" value="0"> in</span></label><label>Trim allowance per drop<span><input id="trim" type="number" min="0" step="any" value="4"> in</span></label><label class="wide">Full matching rolls already owned<span><input id="owned" type="number" min="0" step="1" value="0"></span></label>',resultTitle:'Your wallpaper quantity',result:stats,copyTitle:'Wallpaper is a drop problem, not just an area problem',copy:'<p>Wallpaper is cut into full-height vertical drops. A repeating pattern can force every drop to be longer than the wall itself so the design aligns. This calculator rounds the drop length up to a whole pattern repeat, determines how many drops fit on one roll, and then rounds the project to whole rolls.</p><p>Half-drop matches, unusually large repeats, damaged roll ends, out-of-plumb walls and batch matching can increase the real requirement. Check the label and installation instructions for the exact paper.</p>',faqs:[['Why does pattern repeat increase the roll count?','Each full-height drop may need to be lengthened to the next complete repeat so adjacent strips align.'],['Can I enter wallpaper rolls I already own?','Yes. The purchase-gap result subtracts full matching rolls already owned.'],['Should I divide wall area by roll area?','Area alone can understate the requirement because wallpaper must be cut into full-height drops.']],links:[['/wallpaper','Leftover wallpaper planner','Compare rolls and remnants with the wall you want to cover'],['/how-much-wallpaper-one-roll-cover','How much does one roll cover?','See the drop-based calculation'],['/wallpaper-accent-wall-leftovers','Accent wall from leftovers','Plan a smaller wall around saved wallpaper']]},
 {slug:'trim-cut-calculator',tool:'linear',name:'Trim Cut Calculator',title:'Trim Cut Calculator – Baseboard & Casing Cut List | Leftover',desc:'Free trim cut calculator for baseboard, casing and molding. Enter stock length, kerf and required cut lengths to estimate pieces and see a cut allocation.',eyebrow:'BASEBOARD / CASING / CUT LIST',h1:'Trim Cut Calculator',intro:'Pack baseboard, casing or flat trim cuts onto the stock lengths you can buy or already own, with saw kerf included between cuts.',formTitle:'Pack trim cuts onto stock pieces',fields:linearFields('8','84 x 2\n36 x 1\n30 x 2'),resultTitle:'Your trim cut estimate',result:stats,copyTitle:'A trim cut list catches fit problems that linear footage misses',copy:'<p>Perimeter math is useful for estimating total trim, but it cannot tell you whether a long door casing or uninterrupted wall run fits the pieces you have. A cut list keeps each required length separate and groups those cuts onto stock pieces.</p><p>This tool is best for straight stock. Cope, miter, scarf and pattern-matching allowances may require extra length beyond the finished dimensions you enter. Measure the real runs and add appropriate cutting allowance before relying on the result.</p>',faqs:[['Can I use this for baseboard?','Yes. Enter each finished wall-run length or planned segment and the stock length you buy.'],['Can I use it for door or window casing?','Yes. Enter each casing leg and head length separately so the calculator preserves individual fit.'],['Does it replace the baseboard perimeter calculator?','No. Use the baseboard calculator to estimate room perimeter, then use this cut calculator when individual run lengths matter.']],links:[['/baseboard-trim-calculator','Baseboard calculator','Estimate room perimeter and stock pieces'],['/trim','Leftover trim planner','Compare the plan with full trim pieces and offcuts'],['/trim-door-window','Door and window trim leftovers','Plan casing repairs from saved lengths']]}
];

for(const p of pages) fs.writeFileSync(path.join(out,p.slug+'.html'),toolPage(p));

const guides=[
 {slug:'pressure-treated-deck-board-spacing',name:'Pressure-Treated Deck Board Spacing',title:'Pressure-Treated Deck Board Spacing – Wet vs Dry Boards | Leftover',desc:'Understand pressure-treated deck board spacing for wet versus dry lumber, then use the deck spacing calculator to test board rows and quantity.',h1:'Pressure-Treated Deck Board Spacing: Wet vs Dry',intro:'Pressure-treated lumber can change width as it dries, so the starting gap depends heavily on how wet the boards are when installed.',body:'<span class="eyebrow">WET VS DRY DECKING</span><h2>Do not use one spacing number for every pressure-treated board</h2><p>Fresh pressure-treated boards are often still wet and can shrink across their width as they dry. That is why wet boards are commonly installed tighter than dry or acclimated boards. Dry material needs an intentional drainage and movement gap from the start.</p><p>The safest workflow is to identify the actual moisture condition, check the lumber supplier or installation guidance, and then use that side-to-side gap in a layout calculation. The <a href="/deck-board-calculator">Leftover deck spacing calculator</a> includes separate planning presets for fresh/wet pressure-treated lumber and dry/acclimated wood, while still letting you override the value.</p><h2>What changes when the gap changes?</h2><p>The gap affects how many board rows fit across a fixed deck width. Small changes repeated across twenty or thirty rows can change the final edge condition and sometimes the total board count. Use the calculator before fastening the first course so you can see the row count and coverage.</p><p>This is layout guidance only. Structural framing, joist spacing, fasteners and end gaps are separate requirements.</p>',faqs:[['Should wet pressure-treated deck boards be installed tight?','Fresh wet treated boards are commonly installed tight or very close together because they shrink as they dry, but supplier guidance for the actual lumber controls.'],['What gap should dry pressure-treated boards have?','A small side-to-side gap such as about 1/8 inch is a common planning starting point for dry or acclimated wood; verify the actual lumber guidance.'],['Does this page calculate joist spacing?','No. Joist spacing is structural and separate from the visible side-to-side gap between deck boards.']],links:[['/deck-board-calculator','Deck spacing calculator','Choose wet or dry wood and calculate rows'],['/decking','Decking leftover calculator','Compare the board requirement with boards you already own'],['/decking-leftover-repair','Deck repair planner','Reuse saved deck boards for repair work']]},
 {slug:'composite-deck-board-spacing',name:'Composite Deck Board Spacing',title:'Composite Deck Board Spacing – Gap by Product & Fastener | Leftover',desc:'Plan composite deck board spacing by product and fastener system, then calculate board rows and quantity with the Leftover deck spacing calculator.',h1:'Composite Deck Board Spacing',intro:'Composite and PVC decking do not share one universal gap. Product line, fastener system and installation conditions determine the final spacing.',body:'<span class="eyebrow">PRODUCT-SPECIFIC SPACING</span><h2>Use the exact decking system, not a generic rule</h2><p>Composite and PVC decking is manufactured, so the required side-to-side and end-to-end gaps are specified by the product maker. Hidden-fastener clips can also set the gap automatically. That means a spacing value that is correct for one product can be wrong for another.</p><p>The <a href="/deck-board-calculator">deck spacing calculator</a> includes planning presets for common Trex and TimberTech cases and a manual mode for every other product. The manufacturer’s current installation guide always overrides a generic planning value.</p><h2>Why calculate the layout after choosing the gap?</h2><p>Once you know the required side-to-side gap, the calculator shows how many board rows fit across the deck, how many gaps occur, the linear footage and an estimated stock-board count. This helps avoid discovering an awkward last-row condition after most of the deck is already fastened.</p><p>End gaps, breaker boards, picture frames, joist support, heat exposure and specialty fastening details are outside the scope of the simple row calculation and should be checked separately.</p>',faqs:[['Is 1/8 inch correct for all composite decking?','No. Composite and PVC spacing depends on the exact product line and fastening system.'],['Does a hidden fastener determine spacing?','Many hidden-fastener systems establish a specific side-to-side gap, but you should verify the manufacturer instructions for the exact clip and board.'],['Can I enter my own product gap?','Yes. The Leftover deck spacing calculator has a manual mode so you can use the gap from your current installation guide.']],links:[['/deck-board-calculator','Deck spacing calculator','Apply a product-specific gap to board count'],['/pressure-treated-deck-board-spacing','Pressure-treated board spacing','Compare wet and dry wood behavior'],['/what-can-i-make-with-leftover-deck-boards','Leftover deck board ideas','Find small projects for saved boards']]}
];
for(const p of guides) fs.writeFileSync(path.join(out,p.slug+'.html'),guidePage(p));

const calcJs=`(()=>{const $=id=>document.getElementById(id),n=id=>Number($(id)?.value||0),fmt=(x,d=2)=>Number(x.toFixed(d)).toLocaleString(undefined,{maximumFractionDigits:d});function set(a,b,c,d,summary,note,alloc=''){[['r1',a],['r2',b],['r3',c],['r4',d]].forEach(([id,v])=>$(id).textContent=v);$('trafficSummary').textContent=summary;$('trafficNote').textContent=note;$('trafficAllocation').innerHTML=alloc;}function err(msg){$('trafficError').textContent=msg;$('trafficError').hidden=false;}function clearErr(){$('trafficError').hidden=true;}function area(kind){clearErr();const L=n('roomLength'),W=n('roomWidth'),pl=n('pieceLength'),pw=n('pieceWidth'),waste=n('waste'),perBox=Math.max(1,Math.floor(n('perBox'))),owned=Math.max(0,Math.floor(n('owned')));if(!(L>0&&W>0&&pl>0&&pw>0&&waste>=0&&waste<=100))return err('Enter positive room/surface and piece dimensions. Waste must be 0–100%.');const area=L*W,piece=pl*pw/144,raw=area/piece,need=Math.ceil(raw*(1+waste/100)-1e-10),gap=Math.max(0,need-owned),surplus=Math.max(0,owned-need),boxes=Math.ceil(gap/perBox);const label=kind==='tile'?'tiles':'planks';$('l1').textContent=label+' planned';$('l2').textContent='boxes to buy';$('l3').textContent=label+' already owned';$('l4').textContent=gap?'pieces still needed':'surplus pieces';set(String(need),String(boxes),String(owned),String(gap||surplus),area.toFixed(2)+' sq ft surface · '+piece.toFixed(3)+' sq ft per '+(kind==='tile'?'tile':'plank')+'.',gap?('Purchase gap: '+gap+' '+label+'. Rounded to '+boxes+' box'+(boxes===1?'':'es')+' at '+perBox+' per box.'):('Your entered leftovers cover this quantity estimate with '+surplus+' '+label+' beyond the planned count.'));}
function wallpaper(){clearErr();const ww=n('wallWidth'),wh=n('wallHeight'),rw=n('rollWidth'),rl=n('rollLength'),rep=n('repeat'),trim=n('trim'),owned=Math.max(0,Math.floor(n('owned')));if(!(ww>0&&wh>0&&rw>0&&rl>0&&rep>=0&&trim>=0))return err('Enter positive wall and roll dimensions. Pattern repeat and trim may be zero.');const base=wh*12+trim,drop=rep>0?Math.ceil(base/rep-1e-10)*rep:base,drops=Math.ceil(ww*12/rw-1e-10),per=Math.floor(rl*12/drop+1e-10);if(per<1)return err('The roll is too short to make one full-height drop with these settings.');const rolls=Math.ceil(drops/per),gap=Math.max(0,rolls-owned),surplus=Math.max(0,owned-rolls);$('l1').textContent='full-height drops';$('l2').textContent='rolls required';$('l3').textContent='rolls already owned';$('l4').textContent=gap?'rolls to buy':'surplus rolls';set(String(drops),String(rolls),String(owned),String(gap||surplus),'Adjusted drop length: '+fmt(drop/12,2)+' ft · '+per+' full drop'+(per===1?'':'s')+' per roll.',gap?('You need '+gap+' additional full matching roll'+(gap===1?'':'s')+'.'):('Your entered full rolls cover the estimate with '+surplus+' roll'+(surplus===1?'':'s')+' beyond the calculated minimum.'));}
function parseCuts(txt){const out=[];for(const raw of txt.split(/\n+/)){const line=raw.trim();if(!line)continue;const m=line.match(/^([0-9]+(?:\.[0-9]+)?)\s*(?:x|×|\*)\s*([0-9]+)$/i);if(!m)throw new Error('Use one cut per line as length × quantity, for example: 36 x 4.');const len=Number(m[1]),qty=Number(m[2]);if(!(len>0&&qty>0&&qty<=500))throw new Error('Cut lengths and quantities must be positive.');for(let i=0;i<qty;i++)out.push(len);}return out;}
function linear(){clearErr();const stock=n('stockLength')*12,kerf=n('kerf'),owned=Math.max(0,Math.floor(n('owned')));if(!(stock>0&&kerf>=0))return err('Enter a positive stock length and nonnegative kerf.');let cuts;try{cuts=parseCuts($('cuts').value);}catch(e){return err(e.message);}if(!cuts.length)return err('Enter at least one required cut.');if(cuts.some(x=>x>stock+1e-9))return err('At least one cut is longer than the selected stock piece.');cuts.sort((a,b)=>b-a);const bins=[];for(const cut of cuts){let placed=false;for(const b of bins){const add=cut+(b.cuts.length?kerf:0);if(b.used+add<=stock+1e-9){b.cuts.push(cut);b.used+=add;placed=true;break;}}if(!placed)bins.push({cuts:[cut],used:cut});}const boards=bins.length,gap=Math.max(0,boards-owned),surplus=Math.max(0,owned-boards),waste=bins.reduce((s,b)=>s+(stock-b.used),0);$('l1').textContent='stock pieces required';$('l2').textContent='estimated offcut / waste';$('l3').textContent='stock pieces already owned';$('l4').textContent=gap?'pieces to buy':'surplus stock pieces';const alloc=bins.map((b,i)=>'<div><b>Stock '+(i+1)+'</b>: '+b.cuts.map(x=>fmt(x,3)+' in').join(' + ')+' · '+fmt(stock-b.used,3)+' in remaining</div>').join('');set(String(boards),fmt(waste/12,2)+' ft',String(owned),String(gap||surplus),cuts.length+' cuts packed onto '+boards+' stock piece'+(boards===1?'':'s')+'.',gap?('Purchase gap: '+gap+' stock piece'+(gap===1?'':'s')+'. Longest-first packing is a practical heuristic; verify the real material before cutting.'):('Your entered stock count covers this cut-list estimate with '+surplus+' full piece'+(surplus===1?'':'s')+' beyond the calculated minimum.'),alloc);}
function run(){const t=document.body.dataset.trafficTool;if(t==='tile'||t==='flooring')area(t);else if(t==='wallpaper')wallpaper();else linear();}document.getElementById('trafficRun')?.addEventListener('click',run);document.getElementById('trafficForm')?.addEventListener('input',()=>{if(document.body.dataset.trafficTool!=='linear')run();});run();})();`;
fs.writeFileSync(path.join(out,'traffic-calculators.js'),calcJs);

const hub=`<section class="related seo-priority-links traffic-growth-links" id="popular-calculators"><span class="eyebrow">HIGH-INTENT MATERIAL CALCULATORS</span><h2>Measure the job people are actually trying to finish.</h2><p>Use a focused calculator first, then bring the result into Leftover to compare it with material you already own.</p><div class="related-grid"><a href="/deck-board-calculator"><b>Deck spacing calculator</b><span>Board gap, rows, linear feet and stock boards →</span></a><a href="/lumber-cut-calculator"><b>Lumber cut calculator</b><span>Pack a cut list onto stock boards with kerf →</span></a><a href="/plywood-cut-calculator"><b>Plywood cut calculator</b><span>Plan rectangular sheet cuts and offcuts →</span></a><a href="/flooring-plank-calculator"><b>Flooring plank calculator</b><span>Planks, boxes and leftover-stock gap →</span></a><a href="/tile-coverage-calculator"><b>Tile coverage calculator</b><span>Tiles, boxes, waste and leftovers →</span></a><a href="/wallpaper-roll-calculator"><b>Wallpaper roll calculator</b><span>Drops, pattern repeat and rolls needed →</span></a><a href="/trim-cut-calculator"><b>Trim cut calculator</b><span>Baseboard and casing cut-list fit →</span></a><a href="/baseboard-trim-calculator"><b>Baseboard calculator</b><span>Room perimeter, openings and trim quantity →</span></a><a href="/what-can-i-make"><b>What can I make?</b><span>Start from exact leftover material instead →</span></a></div></section>`;
function patch(file,html){const p=path.join(out,file);if(!fs.existsSync(p))return;let s=fs.readFileSync(p,'utf8');if(s.includes('traffic-growth-links'))return;if(file==='index.html'){s=s.replace('<section class="inventory-lab" id="inventory">',hub+'\n<section class="inventory-lab" id="inventory">');}else{s=s.replace('</main>',html+'\n</main>');}fs.writeFileSync(p,s);}
patch('index.html',hub);
const blocks={
 'lumber.html':related([['/lumber-cut-calculator','Lumber cut calculator','Turn individual cuts into stock-board allocations'],['/what-can-i-make-with-leftover-2x4s','Leftover 2×4 projects','Match saved boards to small builds']]),
 'flooring.html':related([['/flooring-plank-calculator','Flooring plank calculator','Calculate planks and boxes, then subtract leftovers'],['/leftover-flooring-repair','Flooring repair planner','Use matching saved planks for repairs']]),
 'tile.html':related([['/tile-coverage-calculator','Tile coverage calculator','Calculate tiles and boxes, then subtract leftovers'],['/leftover-tile-backsplash','Backsplash from leftover tile','Plan a small surface around saved pieces']]),
 'wallpaper.html':related([['/wallpaper-roll-calculator','Wallpaper roll calculator','Account for drops, trim and pattern repeat'],['/wallpaper-accent-wall-leftovers','Accent wall from leftovers','Reuse saved wallpaper on a smaller wall']]),
 'trim.html':related([['/trim-cut-calculator','Trim cut calculator','Check individual baseboard and casing runs'],['/baseboard-trim-calculator','Baseboard calculator','Estimate perimeter and stock quantity']]),
 'decking.html':related([['/deck-board-calculator','Deck spacing calculator','Determine gap, board rows and quantity'],['/pressure-treated-deck-board-spacing','Pressure-treated spacing','Compare wet and dry wood'],['/composite-deck-board-spacing','Composite deck spacing','Use product-specific gap guidance']]),
 'plywood.html':related([['/plywood-cut-calculator','Plywood cut calculator','Plan panels before cutting a sheet'],['/lumber-cut-calculator','Lumber cut calculator','Plan linear-stock cuts with kerf']]),
 'what-can-i-make.html':hub,
 'deck-board-calculator.html':related([['/pressure-treated-deck-board-spacing','Pressure-treated spacing','Wet vs dry wood gap planning'],['/composite-deck-board-spacing','Composite deck spacing','Product and fastener-specific gap planning'],['/decking','Leftover decking calculator','Compare the requirement with saved boards']]),
 'plywood-cut-calculator.html':related([['/plywood','Leftover plywood planner','Compare the cut plan with sheets and offcuts you own'],['/lumber-cut-calculator','Lumber cut calculator','Optimize straight stock instead of sheets']]),
 'baseboard-trim-calculator.html':related([['/trim-cut-calculator','Trim cut calculator','Preserve individual wall and casing run lengths'],['/trim','Leftover trim planner','Credit full pieces and offcuts you already own']])
};
for(const [f,b] of Object.entries(blocks))patch(f,b);

const sitemap=path.join(out,'sitemap.xml');
if(fs.existsSync(sitemap)){
 let s=fs.readFileSync(sitemap,'utf8');
 const urls=['lumber-cut-calculator','flooring-plank-calculator','tile-coverage-calculator','wallpaper-roll-calculator','trim-cut-calculator','pressure-treated-deck-board-spacing','composite-deck-board-spacing'];
 const rows=urls.filter(u=>!s.includes(`${origin}/${u}</loc>`)).map(u=>`<url><loc>${origin}/${u}</loc><lastmod>2026-09-12</lastmod></url>`).join('\n');
 if(rows)s=s.replace('</urlset>',rows+'\n</urlset>');
 fs.writeFileSync(sitemap,s);
}
console.log('Traffic postbuild: generated 5 calculators, 2 deck-spacing guides, internal link clusters, and sitemap entries.');